# Environnement Web de developpement en PHP 7.0.13 avec Apache
version: '2'
services:

  ssl:
    restart: on-failure
    image: nginx
    container_name: ssl-afl
    ports:
       - "443:443" # Redirection des portes entre l'hote et Docker
    volumes:
       - ./conf/nginx/conf.d:/etc/nginx/conf.d # Configuration nginx
       - ./conf/nginx/ssl:/etc/nginx/ssl # Configuration nginx
    environment:
       - ALLOW_OVERRIDE=true
    links:
       - web:web

  # Web Server PHP 5.6 + Apache 2
  web:
    restart: on-failure
    build: docker/php5apache
    container_name: web-afl
    ports:
       - "80:80" # Redirection des portes entre l'hote et Docker
    volumes:
       - /mnt/filer/php5:/mnt/filer/php5
       - ./logs:/var/log/apache2
       - ./conf/apache/vhosts:/etc/apache2/sites-enabled # Emplacement de VHOST Apache
       - ./conf/apache/certs:/etc/apache2/certs # Emplacement de VHOST Apache
       - ./conf/php/php.ini:/usr/local/etc/php/conf.d/30-custom.ini # PHP ini custom
    environment:
       - ALLOW_OVERRIDE=true
    links:
       - localdb:localdb
       - infogreffe:infogreffe
       - maildev:maildev

  # Database MySQL
  localdb:
      restart: on-failure
      image: mariadb
      container_name: localdb
      volumes:
        - /var/data/mariadb:/var/lib/mysql # Commenter la ligne des volumes pour une base de données non persistente
        - .:/opt/scripts
      ports:
        - "3306:3306"
      environment:
       - MYSQL_ROOT_PASSWORD=root # Mot de passe par defaut pour l'utisateur root

  # Grunt
  grunt:
      restart: on-failure
      build: docker/grunt
      container_name: grunt
      volumes:
          - /mnt/filer/php5/waf_websites/afl:/src

  # To create email during devloppement
  maildev:
      restart: on-failure
      image: djfarrelly/maildev
      container_name: maildev
      ports:
        - "1080:80"

  # PhpMyAdmin
  phpmyadmin:
    restart: on-failure
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - localdb:db
    ports:
      - 8000:80
    volumes:
      - /sessions

  # Infogreffe
  infogreffe:
    restart: on-failure
    build: docker/infogreffe
    container_name: infogreffe
    ports:
      - "2222:22"
    command: test_wkf:123:1000:1000
    volumes:
       - /mnt/filer/php5/waf_webservices/edi/config/id_rsa_test.pub:/home/test_wkf/.ssh/keys/id_rsa.pub

  # navigateur
  googlechrome:
    image: selenium/standalone-chrome
    container_name: googlechrome
    ports:
        - "4444:4444"
    links:
       - web:afl.wkf.net.dev
   