FROM atmoz/sftp
MAINTAINER Alexandre Debril <alexandre.debril@wolterskluwer.com>

RUN mkdir -p /home/test_wkf/Send /home/test_wkf/Receive

RUN chmod -R 777 /home/test_wkf/Send
RUN chmod -R 777 /home/test_wkf/Receive

WORKDIR /home/test_wkf
